- apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc

- apt_repository:
    repo: deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib

- apt:
    name: virtualbox
    state: latest

- include: signed.yml
  with_items:
    - vboxdrv
    - vboxnetflt
    - vboxnetadp
    - vboxpci
