- apt_repository:
    repo: ppa:webupd8team/java
- debconf: 
    name: oracle-java8-installer
    question: shared/accepted-oracle-license-v1-1
    value: true
    vtype: select
- apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - oracle-java8-installer
    - oracle-java8-unlimited-jce-policy
    - oracle-java8-set-default
