- name: update npm completion
  command: npm completion
  register: npm_completion
  notify: save npm completion
- name: save npm completion
  copy:
    dest: /etc/bash_completion.d/npm
    content: "{{ npm_completion.stdout }}"
