- name: Ensure autologin in lightdm 
  copy:
    dest: /etc/lightdm/lightdm.conf
    content: |
      [SeatDefaults]
      user-session=xubuntu
      autologin-user=svpace

- name: Ensure autologin in sudoers
  copy:
    dest: /etc/sudoers.d/disable-password
    content: |
      Defaults	!authenticate

- name: Ensure autologin in polkit
  copy:
    dest: /etc/polkit-1/localauthority/50-local.d/disable-password.pkla
    content: |
      [Disable password]
      Identity=unix-group:sudo
      Action=*
      ResultActive=yes
